### ISSUE TITLE
zopen build results in FileNotFoundError: [Errno 129] EDC5129I No such file or directory.: 'dist/*.whl'

### ISSUE THREAD

**Issue by IgorTodorovskiIBM** [zopencommunity/conanport#1]
I first commented out `export ZOPEN_COMP`
Then ran `zopen build -vv`

Got this:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/itodoro/projects/conanport/conan/.venv/lib/python3.12/site-packages/installer/__main__.py", line 98, in <module>
    _main(sys.argv[1:], "python -m installer")
  File "/home/itodoro/projects/conanport/conan/.venv/lib/python3.12/site-packages/installer/__main__.py", line 86, in _main
    with WheelFile.open(args.wheel) as source:
  File "/home/opnzos/local/pyz/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/itodoro/projects/conanport/conan/.venv/lib/python3.12/site-packages/installer/sources.py", line 162, in open
    with zipfile.ZipFile(path) as f:
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/opnzos/local/pyz/lib/python3.12/zipfile/__init__.py", line 1336, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 129] EDC5129I No such file or directory.: 'dist/*.whl'
```

**Comment by aidanp-21cs** [comment]
Has this been fixed as of #7 ?
